
tap 'cantino/mcfly'
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/core'

if OS.linux?
   tap 'gromgit/fuse'
end

cask 'firefox'
cask 'font-fira-code'
cask 'google-chrome'
cask 'inkscape'
if OS.mac?
    brew 'ntfs-3g'
    brew 'reattach-to-user-namespace'
    cask 'iterm2'
    cask 'karabiner-elements'
    cask 'osxfuse'
    cask 'steam'
end
cask 'qlmarkdown'
cask 'vlc'

brew 'automake'
brew 'bat'
brew 'coreutils'
brew 'ctags'
brew 'fasd'
brew 'ffmpeg'
brew 'findutils'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'git-delta'
brew 'git-extras'
brew 'highlight'
brew 'lame'
brew 'mcfly'
brew 'neovim'
brew 'openssl'
brew 'podofo'
brew 'python3'
brew 'ranger'
brew 'readline'
brew 'rename'
brew 'ripgrep'
brew 'spaceman-diff'
brew 'tidy-html5'
brew 'tmux'
brew 'tree'
brew 'x264'
brew 'xvid'
brew 'youtube-dl'
brew 'zsh'
brew 'zsh-vi-mode'
